parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: upfit
    database_user: upfit
    database_password: upfit
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: d7c766902a1b0c51633956ffeb4a3cfd04197689
    database_path: null
