<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130309120806 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Workout ADD session_id INT DEFAULT NULL, ADD exercise_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Workout ADD CONSTRAINT FK_AB22C2EE613FECDF FOREIGN KEY (session_id) REFERENCES Session (id)");
        $this->addSql("ALTER TABLE Workout ADD CONSTRAINT FK_AB22C2EEE934951A FOREIGN KEY (exercise_id) REFERENCES Exercise (id)");
        $this->addSql("CREATE INDEX IDX_AB22C2EE613FECDF ON Workout (session_id)");
        $this->addSql("CREATE INDEX IDX_AB22C2EEE934951A ON Workout (exercise_id)");
        $this->addSql("ALTER TABLE Session ADD user_id INT DEFAULT NULL, ADD club_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Session ADD CONSTRAINT FK_1FF9EC48A76ED395 FOREIGN KEY (user_id) REFERENCES User (id)");
        $this->addSql("ALTER TABLE Session ADD CONSTRAINT FK_1FF9EC4861190A32 FOREIGN KEY (club_id) REFERENCES Club (id)");
        $this->addSql("CREATE INDEX IDX_1FF9EC48A76ED395 ON Session (user_id)");
        $this->addSql("CREATE INDEX IDX_1FF9EC4861190A32 ON Session (club_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Session DROP FOREIGN KEY FK_1FF9EC48A76ED395");
        $this->addSql("ALTER TABLE Session DROP FOREIGN KEY FK_1FF9EC4861190A32");
        $this->addSql("DROP INDEX IDX_1FF9EC48A76ED395 ON Session");
        $this->addSql("DROP INDEX IDX_1FF9EC4861190A32 ON Session");
        $this->addSql("ALTER TABLE Session DROP user_id, DROP club_id");
        $this->addSql("ALTER TABLE Workout DROP FOREIGN KEY FK_AB22C2EE613FECDF");
        $this->addSql("ALTER TABLE Workout DROP FOREIGN KEY FK_AB22C2EEE934951A");
        $this->addSql("DROP INDEX IDX_AB22C2EE613FECDF ON Workout");
        $this->addSql("DROP INDEX IDX_AB22C2EEE934951A ON Workout");
        $this->addSql("ALTER TABLE Workout DROP session_id, DROP exercise_id");
    }
}
