<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130331111502 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Stage (id INT AUTO_INCREMENT NOT NULL, program_id INT DEFAULT NULL, exercise_id INT DEFAULT NULL, position SMALLINT NOT NULL, INDEX IDX_3BDBC6D3EB8070A (program_id), INDEX IDX_3BDBC6DE934951A (exercise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE Program (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Stage ADD CONSTRAINT FK_3BDBC6D3EB8070A FOREIGN KEY (program_id) REFERENCES Program (id)");
        $this->addSql("ALTER TABLE Stage ADD CONSTRAINT FK_3BDBC6DE934951A FOREIGN KEY (exercise_id) REFERENCES Exercise (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Stage DROP FOREIGN KEY FK_3BDBC6D3EB8070A");
        $this->addSql("DROP TABLE Stage");
        $this->addSql("DROP TABLE Program");
    }
}
