<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130309123155 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("CREATE TABLE Muscle (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Exercise ADD muscle_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Exercise ADD CONSTRAINT FK_57ACB74A354FDBB4 FOREIGN KEY (muscle_id) REFERENCES Muscle (id)");
        $this->addSql("CREATE INDEX IDX_57ACB74A354FDBB4 ON Exercise (muscle_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE Exercise DROP FOREIGN KEY FK_57ACB74A354FDBB4");
        $this->addSql("DROP TABLE Muscle");
        $this->addSql("DROP INDEX IDX_57ACB74A354FDBB4 ON Exercise");
        $this->addSql("ALTER TABLE Exercise DROP muscle_id");
    }
}
