<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130311202647 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Adjustment ADD machine_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Adjustment ADD CONSTRAINT FK_C6A47BC6F6B75B26 FOREIGN KEY (machine_id) REFERENCES Adjustment (id)");
        $this->addSql("CREATE INDEX IDX_C6A47BC6F6B75B26 ON Adjustment (machine_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Adjustment DROP FOREIGN KEY FK_C6A47BC6F6B75B26");
        $this->addSql("DROP INDEX IDX_C6A47BC6F6B75B26 ON Adjustment");
        $this->addSql("ALTER TABLE Adjustment DROP machine_id");
    }
}
