<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130309132235 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Session DROP FOREIGN KEY FK_1FF9EC4861190A32");
        $this->addSql("ALTER TABLE Session DROP FOREIGN KEY FK_1FF9EC48A76ED395");
        $this->addSql("DROP INDEX IDX_1FF9EC48A76ED395 ON Session");
        $this->addSql("DROP INDEX IDX_1FF9EC4861190A32 ON Session");
        $this->addSql("ALTER TABLE Session ADD member_id INT DEFAULT NULL, DROP club_id, DROP user_id");
        $this->addSql("ALTER TABLE Session ADD CONSTRAINT FK_1FF9EC487597D3FE FOREIGN KEY (member_id) REFERENCES Member (id)");
        $this->addSql("CREATE INDEX IDX_1FF9EC487597D3FE ON Session (member_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Session DROP FOREIGN KEY FK_1FF9EC487597D3FE");
        $this->addSql("DROP INDEX IDX_1FF9EC487597D3FE ON Session");
        $this->addSql("ALTER TABLE Session CHANGE member_id user_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Session ADD CONSTRAINT FK_1FF9EC4861190A32 FOREIGN KEY (club_id) REFERENCES Club (id)");
        $this->addSql("ALTER TABLE Session ADD CONSTRAINT FK_1FF9EC48A76ED395 FOREIGN KEY (user_id) REFERENCES User (id)");
        $this->addSql("CREATE INDEX IDX_1FF9EC48A76ED395 ON Session (user_id)");
        $this->addSql("CREATE INDEX IDX_1FF9EC4861190A32 ON Session (club_id)");
    }
}
