<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130311203138 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Exercise ADD machine_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Exercise ADD CONSTRAINT FK_57ACB74AF6B75B26 FOREIGN KEY (machine_id) REFERENCES Machine (id)");
        $this->addSql("CREATE INDEX IDX_57ACB74AF6B75B26 ON Exercise (machine_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Exercise DROP FOREIGN KEY FK_57ACB74AF6B75B26");
        $this->addSql("DROP INDEX IDX_57ACB74AF6B75B26 ON Exercise");
        $this->addSql("ALTER TABLE Exercise DROP machine_id");
    }
}
