<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130331114642 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Program ADD club_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Program ADD CONSTRAINT FK_5D504E1861190A32 FOREIGN KEY (club_id) REFERENCES Club (id)");
        $this->addSql("CREATE INDEX IDX_5D504E1861190A32 ON Program (club_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Program DROP FOREIGN KEY FK_5D504E1861190A32");
        $this->addSql("DROP INDEX IDX_5D504E1861190A32 ON Program");
        $this->addSql("ALTER TABLE Program DROP club_id");
    }
}
