<?php

namespace Bpaulin\UpfitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends AbstractRepository
{
    /**
     * @param  array $get
     * @param  bool  $flag
     * @return array
     */
    public function ajaxTable(array $get, $flag = false, $where='')
    {
        return $this->abstractAjaxTable($get, 'BpaulinUpfitBundle:Member', $flag, $where);
    }

    /**
     * @return int
     */
    public function getCount($where='')
    {
        if ($where) {
            $where = " WHERE m.$where";
        }
        $aResultTotal = $this->getEntityManager()
            ->createQuery("SELECT COUNT(m) FROM BpaulinUpfitBundle:Member m $where")
            ->setMaxResults(1)
            ->getResult();

        return $aResultTotal[0][1];
    }
}
