<?php

namespace Bpaulin\UpfitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
    public function findByUser($user)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT s FROM BpaulinUpfitBundle:Session s JOIN s.member m WHERE m.user=:user')
            ->setParameter('user', $user)
            ->getResult();
    }
}
